<?php
/**
 * @Author 张超.
 * @Copyright http://www.zhangchao.name
 * @Email 416716328@qq.com
 * @DateTime 2018/5/22 11:58
 * @Desc
 */

namespace app\common\controller;


use Firebase\JWT\JWT;
use think\Controller;

class App extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //token验证
        $config = get_config("api", "develop", "not_allow_token");
        $modul = $this->request->controller() . "/" . $this->request->action();
        if (in_array($modul, $config)) {
            return true;
        }
        $token = $this->request->header("token");
        if (!isset($token)) {
            $this->ajaxRuturn(400,"Token验证无效！");
        }
        $verifyResult = $this->verify_token($token,get_config("api", "develop", "token_key"));
        if ($verifyResult !== true){
            $this->ajaxRuturn(400,"Token验证失败！".$token);
        }
    }

    /**
     * @author by 张超 <Email:416716328@qq.com web:http://www.zhangchao.name>
     * @name 方法注释
     * @version 1.0.0
     * @funName created_token
     * @param $params 需要生成token的对象数组
     * @param $authKey 生成token的盐值
     * @return  Obj
     */
    public function created_token($params, $authKey)
    {
        $iat = strtotime(date("Y-m-d H:i:s"));
        $nbf = strtotime(date("Y-m-d H:i:s", strtotime("2 seconds")));
        $time = time();
        $token = array(
            "iss" => "https://www.zhangchao.name",//甲方
            "aud" => "https://www.zhangchao.name",//乙方
            "iat" => $time,
            "nbf" => $time + 10,
            'exp' => strtotime(date("Y-m-d H:i:s", strtotime("+1 week"))),
            'data' => $params
        );
        try {
            $jwt = JWT::encode($token, $authKey);
            if (is_string($jwt)) {
                return $jwt;
            } else {
                return false;
            }
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * @author by 张超 <Email:416716328@qq.com web:http://www.zhangchao.name>
     * @name 方法注释
     * @version 1.0.0
     * @funName verify_token
     * @param $jwt 之前生成的token
     * @param $authKey token加密的盐值
     * @return  Obj
     */
    public function verify_token($jwt, $authKey)
    {
        try {
            $decoded = JWT::decode($jwt, $authKey, array('HS256'));
            $token = json_decode(json_encode($decoded), true);
            if (is_array($token) && count($token) > 0) {
                return true;
            } else {
                return false;
            }
        } catch (\Exception $e) {
            return false;
        }
    }
    /**
     * @author by 张超 <Email:416716328@qq.com web:http://www.zhangchao.name>
     * @name 定义ajax请求返回的数据类型
     * @version 1.0.0
     * @funName ajaxRuturn
     * @param $code 状态码 200成功 400失败
     * @param $msg 返回的提示消息
     * @param $data 需要返回的数据
     * @return  Obj
     */
    public function ajaxRuturn($code, $msg, $data = [])
    {
        header('Content-Type:application/json; charset=utf-8');
        $array['status'] = $code;
        $array['msg'] = $msg;
        $array['data'] = $data;
        exit(json_encode($array));
    }
}