<?php
/**
 * @Author 张超.
 * @Copyright http://www.zhangchao.name
 * @Email 416716328@qq.com
 * @DateTime 2018/5/12 13:43
 * @Desc
 */

namespace app\run\controller;


use app\common\controller\Run;
use app\run\model\AuthGroupAccess;
use app\run\model\MenusRule;

class AuthGroup extends Run
{
    protected function initialize()
    {
        return parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function lists()
    {
        if ($this->request->isAjax()) {
            //根据条件查询数据、之后再进行分页
            if (input("get.title")) {
                $map[] = ['title', "like", "%" . input("get.title") . "%"];
            }
            $map[] = ['status', "eq", 1];
            //读取菜单列表
            $model = new \app\run\model\AuthGroup();
            $list = $model->where($map)->order("id desc")->select()->toArray();
            //分页
            $result = paging(input("get.page"), input("get.limit"), $list);
            $this->layAjax(200, "数据获取成功！", count($list), $result);
        }else{
            return $this->fetch();
        }
    }

    public function created()
    {
        if ($this->request->isAjax()) {
            $model = new \app\run\model\AuthGroup();
            $result = $model->allowField(true)->save(input("post."));
            if ($result){
                $this->ajaxRuturn(200,"权限组添加成功！");
            }else{
                $this->ajaxRuturn(400,"权限组添加失败！");
            }
        } else {
            return $this->fetch();
        }
    }
    public function getAuth(){
        $rules = new MenusRule();
        $data = $rules->select()->toArray();
        foreach ($data as $key=>$val){
            $data[$key]['rule'] = $val['name'];
            $data[$key]['name'] = $val['title'];
            unset($data[$key]['icon']);
        }
        if ($data){
            $this->ajaxRuturn(200,"数据获取成功！",$data);
        }else{
            $this->ajaxRuturn(400,"数据获取失败！");
        }
    }
    public function modify(){
        if ($this->request->isAjax()){
            $model = new \app\run\model\AuthGroup();
            $result = $model->allowField(true)->save(input("post."),['id'=>input("post.id")]);
            if ($result){
                $this->ajaxRuturn(200,"权限组更新成功！");
            }else{
                $this->ajaxRuturn(400,"权限组更新失败！");
            }
        }else{
            $auth_group = new \app\run\model\AuthGroup();
            //组装条件
            $map[] = ['id','eq',input("get.id")];
            $rules = $auth_group->where($map)->find();
            $rules['rules'] = explode(",",$rules['rules']);
            $this->assign("rules",json_encode($rules));
            return $this->fetch();
        }
    }
    public function delete(){
        if ($this->request->isAjax()){
            $post = input("post.id");
            $ids = explode(",",ltrim($post,","));
            $model = new \app\run\model\AuthGroup();
            //组装条件
            $map[] = ['id',"in",$ids];
            $result = $model->where($map)->delete();
            if ($result){
                $this->ajaxRuturn(200,"删除成功！");
            }else{
                $this->ajaxRuturn(400,"删除失败！");
            }
        }
    }
}