<?php
/**
 * @Author 张超.
 * @Copyright http://www.zhangchao.name
 * @Email 416716328@qq.com
 * @DateTime 2018/5/8 16:43
 * @Desc
 */

namespace app\run\controller;


use app\common\controller\Run;
use app\run\model\MenusRule;
use think\facade\Config;

class Member extends Run
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function lists()
    {
        return $this->fetch();
    }
}