<?php
/**
 * @Author 张超.
 * @Copyright http://www.zhangchao.name
 * @Email 416716328@qq.com
 * @DateTime 2018/5/9 21:20
 * @Desc
 */

namespace app\run\model;
use think\Model;

class AuthGroupAccess extends Model
{
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}