<?php
/**
 * Created by PhpStorm.
 * User: slkj
 * Date: 2019/3/19
 * Time: 10:51
 */

namespace app\run\model;


use think\Model;

class NewsClass extends Model
{
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}